# combo.yml
---
- hosts: combo
  gather_facts: no
  remote_user: ubuntu
  tasks:
# 1. common
# 1.1 apt packages related
# 1.1.1 update the apt-get
   - name: apt-get update
     become: true
     apt:
       update_cache: yes
# 1.1.2 install the common apt packages
   - name: install the packages using apt modules
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - python3-pip
       - git
       - vim
# 1.2 directory related
# 1.2.1 mkdir the directory
   - name: mkdir the mount point
     become: true
     file:
       path: /data
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
# 1.2.2 mount the volume on the directory
# 1.2.3 mkdir the workspace
   - name: mkdir the /data/workspace
     become: true
     file:
       path: "{{ item }}"
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
     with_items:
      - /data/workspace
      - /data/log
      - /data/log/couchdb
      - /data/log/streamer
      - /data/log/searcher
## 1.3 git
   - name: checkout from github
     command: git clone https://youshaox:f7c1b12e440eefc32882bd423415c0b83a616d33@github.com/youshaox/cluster_and_cloud_2018.git
     args:
       chdir: /data/workspace
       creates: /data/workspace/cluster_and_cloud_2018
## 1.4 sentimental analysis
   - name: sentimental anlysis related
     command: pip3 install {{item}}
     with_items:
       - couchdb
       - cloudant
       - textblob
       - Shapely
       - Point
       - pandas
       - tweepy
# 2 specific: couchdb
## 2.1 apt-get install couchdb related packages
   - name: install the packages needed by couchdb
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - build-essential
       - pkg-config
       - runit
       - erlang
       - libicu-dev
       - libmozjs185-dev
       - libcurl4-openssl-dev
## 2.2 run the shell script
   - name: install couchdb via shell
     shell: |
       cd /data/workspace
       wget http://apache.mirror.digitalpacific.com.au/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz
       tar -zxvf apache-couchdb-2.1.1.tar.gz
       cd apache-couchdb-2.1.1/
       sudo rm -rf /usr/lib/erlang/man
       ./configure && make release
       cd /data/workspace/apache-couchdb-2.1.1/rel/couchdb/etc
       sed -i "s/;admin = mysecretpassword/admin = cdurq48YWLWtZtd/g" local.ini
#       sed -i "s/;admin = mysecretpassword/admin = admin/g" local.ini
       sed -i 's/127.0.0.1/0.0.0.0/g' default.ini
       cd /data/workspace/apache-couchdb-2.1.1/rel/couchdb/releases/2.1.1;rm -rf sys.config
       echo '[' >> sys.config
       echo '    {lager, [' >> sys.config
       echo '        {error_logger_hwm, 1000},' >> sys.config
       echo '        {error_logger_redirect, true},' >> sys.config
       echo '        {handlers, [' >> sys.config
       echo '            {lager_console_backend, [debug, {' >> sys.config
       echo '                lager_default_formatter,' >> sys.config
       echo '                [' >> sys.config
       echo '                    date, " ", time,' >> sys.config
       echo '                    " [", severity, "] ",' >> sys.config
       echo '                    node, " ", pid, " ",' >> sys.config
       echo '                    message,' >> sys.config
       echo '                    "\\n"' >> sys.config
       echo '                ]' >> sys.config
       echo '            }]}' >> sys.config
       echo '        ]},' >> sys.config
       echo '        {inet_dist_listen_min, 9100},' >> sys.config
       echo '        {inet_dist_listen_max, 9200}' >> sys.config
       echo '    ]}' >> sys.config
       echo '].' >> sys.config
# 2.3 customised configure
   - name: sed the vm.args
     become: true
     warn: False
     shell: |
       sed -i "s/-name couchdb@127.0.0.1/-name couchdb@$(ip route get 8.8.8.8 | awk '{print $NF; exit}')/g" /data/workspace/apache-couchdb-2.1.1/rel/couchdb/etc/vm.args
# 3. run
   - name: run the couchdb, streamer, seacher
     ignore_errors: True
     shell: |
       cd /data/log/couchdb;nohup sh /data/workspace/apache-couchdb-2.1.1/rel/couchdb/bin/couchdb 2>&1 &
       sleep 3s
       cd /data/log/stream;nohup python3 /data/workspace/cluster_and_cloud_2018/3_crawler/crawler.py /data/workspace/cluster_and_cloud_2018/3_crawler/configure.json stream 0 &
       cd /data/log/searcher;nohup python3 /data/workspace/cluster_and_cloud_2018/3_crawler/crawler.py /data/workspace/cluster_and_cloud_2018/3_crawler/configure.json search 1 &