# couchdb.yml
---
- hosts: couchdb
  gather_facts: no
  remote_user: ubuntu
  tasks:
# 1. common
# 1.1 apt packages related
# 1.1.1 update the apt-get
   - name: apt-get update
     become: true
     apt:
       update_cache: yes
# 1.1.2 install the common apt packages
   - name: install the packages using apt modules
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - python3-pip
       - git
       - vim
# 1.2 directory related
# 1.2.1 mkdir the directory
   - name: mkdir the data directory
     become: true
     file:
       path: /data
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
# 1.2.2 mount the volume on the directory
   - name: mkdir the mount point
     become: true
     shell: |
       mkfs.ext4 /dev/vdc
       mount /dev/vdc /data
       sleep 3
   - name: change owner of directory to ubuntu
     become: true
     command: chown -R ubuntu:ubuntu /data
# 1.2.3 mkdir the workspace
   - name: mkdir the /data/workspace
     become: true
     file:
       path: "{{ item }}"
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
     with_items:
      - /data/workspace
## 1.3 git
   - name: checkout from github
     command: git clone https://github.com/youshaox/cluster_and_cloud_2018.git
     args:
       chdir: /data/workspace
       creates: /data/workspace/cluster_and_cloud_2018
## 1.4 sentimental analysis
   - name: sentimental anlysis related
     command: pip3 install {{item}}
     with_items:
       - couchdb
       - cloudant
       - textblob
       - Shapely
       - Point
       - pandas
       - emoji
# 2 specific: couchdb
## 2.1 apt-get install couchdb related packages
   - name: install the packages needed by couchdb
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - build-essential
       - pkg-config
       - runit
       - erlang
       - libicu-dev
       - libmozjs185-dev
       - libcurl4-openssl-dev
## 2.2 run the shell script
   - name: install couchdb via shell
     shell: |
       cd /data/workspace
       wget http://apache.mirror.digitalpacific.com.au/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz
       tar -zxvf apache-couchdb-2.1.1.tar.gz
       cd apache-couchdb-2.1.1/
       sudo rm -rf /usr/lib/erlang/man
       ./configure && make release
       cd /data/workspace/apache-couchdb-2.1.1/rel/couchdb/etc
       sed -i "s/;admin = mysecretpassword/admin = cdurq48YWLWtZtd/g" local.ini
       sed -i 's/127.0.0.1/0.0.0.0/g' default.ini
       cd /data/workspace/apache-couchdb-2.1.1/rel/couchdb/releases/2.1.1;rm -rf sys.config
       echo '[' >> sys.config
       echo '    {lager, [' >> sys.config
       echo '        {error_logger_hwm, 1000},' >> sys.config
       echo '        {error_logger_redirect, true},' >> sys.config
       echo '        {handlers, [' >> sys.config
       echo '            {lager_console_backend, [debug, {' >> sys.config
       echo '                lager_default_formatter,' >> sys.config
       echo '                [' >> sys.config
       echo '                    date, " ", time,' >> sys.config
       echo '                    " [", severity, "] ",' >> sys.config
       echo '                    node, " ", pid, " ",' >> sys.config
       echo '                    message,' >> sys.config
       echo '                    "\\n"' >> sys.config
       echo '                ]' >> sys.config
       echo '            }]}' >> sys.config
       echo '        ]},' >> sys.config
       echo '        {inet_dist_listen_min, 9100},' >> sys.config
       echo '        {inet_dist_listen_max, 9200}' >> sys.config
       echo '    ]}' >> sys.config
       echo '].' >> sys.config
# 2.3 customised configure
   - name: sed the vm.args
     become: true
     warn: False
     shell: |
       sed -i "s/-name couchdb@127.0.0.1/-name couchdb@$(ip route get 8.8.8.8 | awk '{print $NF; exit}')/g" /data/workspace/apache-couchdb-2.1.1/rel/couchdb/etc/vm.args
# 3. run the couchdb
   - name: run the couchdb (part1)
     become: true
     shell: |
       adduser --system --no-create-home --shell /bin/bash --group --gecos "CouchDB Administrator" couchdb
       cp -R /data/workspace/apache-couchdb-2.1.1/rel/couchdb /home/couchdb
       chown -R couchdb:couchdb /home/couchdb
       find /home/couchdb -type d -exec chmod 0770 {} \;
       sh -c 'chmod 0644 /home/couchdb/etc/*'
       mkdir /var/log/couchdb
       chown couchdb:couchdb /var/log/couchdb
       mkdir /etc/sv/couchdb
       mkdir /etc/sv/couchdb/log
   - name: run the couchdb (part2)
     shell: |
       echo "#!/bin/sh" >> /data/workspace/apache-couchdb-2.1.1/run
       echo "export HOME=/home/couchdb" >> /data/workspace/apache-couchdb-2.1.1/run
       echo "exec 2>&1" >> /data/workspace/apache-couchdb-2.1.1/run
       echo "exec chpst -u couchdb /home/couchdb/bin/couchdb" >> /data/workspace/apache-couchdb-2.1.1/run
   - name: run the couchdb (part3)
     shell: |
       echo "#!/bin/sh" >> /data/workspace/apache-couchdb-2.1.1/log_run
       echo "exec svlogd -tt /var/log/couchdb" >> /data/workspace/apache-couchdb-2.1.1/log_run
   - name: run the couchdb (part4)
     become: true
     shell: |
       cd /data/workspace
       mv apache-couchdb-2.1.1/run /etc/sv/couchdb/run
       mv apache-couchdb-2.1.1/log_run /etc/sv/couchdb/log/run
       chmod u+x /etc/sv/couchdb/run
       chmod u+x /etc/sv/couchdb/log/run
       ln -s /etc/sv/couchdb/ /etc/service/couchdb
       sleep 5
       sv status couchdb