# searcher.yml
# 定下授权序号
---
- hosts: searcher
  gather_facts: no
  remote_user: ubuntu
  vars:
    searcher_auth: "{{ hostvars[groups['searcher'][0]].auth }}"
  tasks:
# 1. common
# 1.1 apt packages related
# 1.1.1 update the apt-get
   - name: apt-get update
     become: true
     apt:
       update_cache: yes
# 1.1.2 install the common apt packages
   - name: install the packages using apt modules
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - python3-pip
       - git
# 1.2 directory related
# 1.2.1 mkdir the directory
   - name: mkdir the mount point
     become: true
     file:
       path: /data
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
   - name: mkdir the /data/workspace
     become: true
     file:
       path: "{{ item }}"
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
     with_items:
      - /data/workspace
      - /data/log
      - /data/log/searcher
## 1.3 git
   - name: checkout from github
     command: git clone https://github.com/youshaox/cluster_and_cloud_2018.git
     args:
       chdir: /data/workspace
       creates: /data/workspace/cluster_and_cloud_2018
## 1.4 sentimental analysis
   - name: sentimental anlysis related
     command: pip3 install {{item}}
     with_items:
       - couchdb
       - cloudant
       - textblob
       - Shapely
       - Point
       - pandas
       - emoji
# 2 specific: crawler-searcher
## 2.1 install the searcher related packages
   - name: install the searcher-related packages
     command: pip3 install {{item}}
     with_items:
       - tweepy
# 3. run
   - name: run the searcher
     ignore_errors: True
     shell: |
       nohup python3 /data/workspace/cluster_and_cloud_2018/3_crawler/crawler.py /data/workspace/cluster_and_cloud_2018/3_crawler/configure.json search {{ searcher_auth }} &
     args:
       chdir: /data/log/searcher