# couchdb.yml
---
- hosts: couchdb
  gather_facts: no
  remote_user: ubuntu
  vars:
    couchdb1_name: "{{ hostvars[groups['couchdb'][0]].couchdb_name }}"
    couchdb1_ip: "{{ hostvars[groups['couchdb'][0]].couchdb_ip }}"
  tasks:
# 1. common
# 1.1 apt packages related
# 1.1.1 update the apt-get
   - name: apt-get update
     become: true
     apt:
       update_cache: yes
# 1.1.2 install the common apt packages
   - name: install the packages using apt modules
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - python3-pip
       - git
       - vim
# 1.2 directory related
# 1.2.1 mkdir the directory
   - name: mkdir the mount point
     become: true
     file:
       path: /data
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
# 1.2.2 mount the volume on the directory

# 1.2.3 mkdir the workspace
   - name: mkdir the /data/workspace
     become: true
     file:
       path: "{{ item }}"
       state: directory
       owner: ubuntu
       group: ubuntu
       mode: 0755
     with_items:
      - /data/workspace
      - /data/log
      - /data/log/couchdb
## 1.3 git
   - name: checkout from github
     command: git clone https://youshaox:f7c1b12e440eefc32882bd423415c0b83a616d33@github.com/youshaox/cluster_and_cloud_2018.git
     args:
       chdir: /data/workspace
       creates: /data/workspace/cluster_and_cloud_2018
## 1.4 sentimental analysis
   - name: sentimental anlysis related
     command: pip3 install {{item}}
     with_items:
       - couchdb
       - cloudant
       - textblob
       - Shapely
       - Point
       - pandas
   - name: textblob.download_corpora
     become: true
     command: python3 -m textblob.download_corpora

# 2 specific: couchdb
## 2.1 apt-get install couchdb related packages
   - name: install the packages needed by couchdb
     become: true
     apt: name={{item}} state=latest update_cache=yes
     with_items:
       - build-essential
       - pkg-config
       - runit
       - erlang
       - libicu-dev
       - libmozjs185-dev
       - libcurl4-openssl-dev
## 2.2 run the shell script
   - name: install couchdb via shell
     become: true
     command: sh /data/workspace/cluster_and_cloud_2018/1_vm_scripts/4_ansible/test/couchdb-setup.sh
# 2.3 customised configure
   - name: sed the vm.args
     become: true
     command: sed -i "s/-name couchdb@127.0.0.1/-name {{ couchdb1_name }}@{{ couchdb1_ip}}/g" /data/workspace/apache-couchdb-2.1.1/rel/couchdb/etc/vm.args

# 3. run
   - name: run the couchdb
     command: nohup sh /data/workspace/apache-couchdb-2.1.1/rel/couchdb/bin/couchdb 2>&1 &
     args:
       chdir: /data/log/couchdb